version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      bash -c "flask db upgrade && flask run --host=0.0.0.0 --port=3000"
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
